src/util/file.o: src/util/file.cc src/util/file.h src/util/common.h \
  extlib/glog/src/glog/logging.h extlib/gflags/src/gflags/gflags.h \
  extlib/glog/src/glog/log_severity.h extlib/glog/src/glog/vlog_is_on.h \
  src/util/hash.h src/util/common.pb.h
src/util/rpc.o: src/util/rpc.cc src/util/rpc.h src/util/common.h \
  extlib/glog/src/glog/logging.h extlib/gflags/src/gflags/gflags.h \
  extlib/glog/src/glog/log_severity.h extlib/glog/src/glog/vlog_is_on.h \
  src/util/hash.h /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpio.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpicxx.h src/util/fake-mpi.h
src/util/common.pb.o: src/util/common.pb.cc src/util/common.pb.h
src/util/fake-mpi.o: src/util/fake-mpi.cc src/util/fake-mpi.h \
  src/util/common.h extlib/glog/src/glog/logging.h \
  extlib/gflags/src/gflags/gflags.h extlib/glog/src/glog/log_severity.h \
  extlib/glog/src/glog/vlog_is_on.h src/util/hash.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpio.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpicxx.h
src/util/common.o: src/util/common.cc src/util/common.h \
  extlib/glog/src/glog/logging.h extlib/gflags/src/gflags/gflags.h \
  extlib/glog/src/glog/log_severity.h extlib/glog/src/glog/vlog_is_on.h \
  src/util/hash.h src/util/file.h src/util/common.pb.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpio.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpicxx.h
src/worker/worker.o: src/worker/worker.cc src/util/common.h \
  extlib/glog/src/glog/logging.h extlib/gflags/src/gflags/gflags.h \
  extlib/glog/src/glog/log_severity.h extlib/glog/src/glog/vlog_is_on.h \
  src/util/hash.h src/util/fake-mpi.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpio.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpicxx.h src/worker/worker.h \
  src/util/rpc.h src/worker/worker.pb.h src/worker/table-internal.h \
  src/worker/table.h src/worker/kernel.h
src/worker/kernel.o: src/worker/kernel.cc src/worker/kernel.h \
  src/util/common.h extlib/glog/src/glog/logging.h \
  extlib/gflags/src/gflags/gflags.h extlib/glog/src/glog/log_severity.h \
  extlib/glog/src/glog/vlog_is_on.h src/util/hash.h
src/worker/worker.pb.o: src/worker/worker.pb.cc src/worker/worker.pb.h
src/worker/table-internal.o: src/worker/table-internal.cc \
  src/util/common.h extlib/glog/src/glog/logging.h \
  extlib/gflags/src/gflags/gflags.h extlib/glog/src/glog/log_severity.h \
  extlib/glog/src/glog/vlog_is_on.h src/util/hash.h \
  src/worker/table-internal.h src/worker/table.h src/util/rpc.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpio.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpicxx.h src/worker/worker.pb.h
src/test/test-shortest-path.o: src/test/test-shortest-path.cc \
  src/util/common.h extlib/glog/src/glog/logging.h \
  extlib/gflags/src/gflags/gflags.h extlib/glog/src/glog/log_severity.h \
  extlib/glog/src/glog/vlog_is_on.h src/util/hash.h src/util/file.h \
  src/util/common.pb.h src/worker/worker.h src/util/rpc.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpio.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpicxx.h src/worker/worker.pb.h \
  src/worker/table-internal.h src/worker/table.h src/master/master.h \
  src/worker/kernel.h
src/master/master.o: src/master/master.cc src/master/master.h \
  src/worker/kernel.h src/util/common.h extlib/glog/src/glog/logging.h \
  extlib/gflags/src/gflags/gflags.h extlib/glog/src/glog/log_severity.h \
  extlib/glog/src/glog/vlog_is_on.h src/util/hash.h src/worker/worker.h \
  src/util/rpc.h /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpio.h \
  /home/power/local/mpich2/include/mpi.h \
  /home/power/local/mpich2/include/mpicxx.h src/worker/worker.pb.h \
  src/worker/table-internal.h src/worker/table.h
